spring:
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path= /products/**
        - id: marketplace
          uri: lb://market-place
          predicates:
            - Path= /marketplaces/**
server:
  port: 8080