spring:
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: product
#          uri: http://localhost:9010/
          uri: lb://product-service
          predicates:
            - Path= /products/**
         - id: marketplace
#          uri: http://localhost:9010/
          uri: lb://market-place-service
          predicates:
            - Path= /marketplaces/**
server:
  port: 80